version: "3.3"

services:
  nginx: 
    build: ./FullStackAppFrontEnd/
    ports: 
      - "80:80"
    depends_on:
      - api

  api:
    image: api
    build: ./FullStackApp/
    ports:
      - "8080:8080"
    environment:
      DB_NAME: fullstack
      DB_HOST: mysql-db
      DB_USERNAME: newuser
      DB_PASSWORD: password
    restart: on-failure 
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstack
      MYSQL_USER: newuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
